README.md

fix(readme): fix grammar

---

src/app/app.component.ts

Bug fix
Issue #17 - BaThemeConfig is not being injected. This prevents custom themes from working properly.
BaThemeConfig is injected and custom themes will now load properly.

Inject BaThemeConfig into the App. Fixes #17

---

docs/contents/articles/002-installation-guidelines/index.md

Docs Update
Missing global bower install.
Added bower install line.

Add bower to global npm package list

---

docs/contents/articles/015-sidebar/index.md

Docs update
There are some typos and English grammar that can be improved 
I fixed the typos and improved the grammar
I am happy to do the same to the other docs to improve readability, but I will wait until this PR is approved and merged to do so (in case the help is not wanted).

Copy-editing and fixed some typos

---

Dockerfile
docs/contents/articles/002-installation-guidelines/index.md
docs/contents/articles/012-project-structure/index.md
src/main.browser.ts
src/vendor.browser.ts

Hi,
In the commit akveo/ng2-admin@e7fca6d, we moved to @types but it remains some traces of typings in the project.
This commit tries to remove them.

Remove old traces of typings.

---

src/app/theme/components/baContentTop/baContentTop.html

Use the routerLink directive instead of a href attribute

Update baContentTop.html to comply with ng2 links

---

src/app/theme/components/baAmChart/baAmChart.component.ts

Bug
https://github.com/akveo/ng2-admin/issues/135
App loaded correctly in microsoft edge

#135 Fixed loading for IE

---

config/webpack.common.js
package.json
src/app/theme/components/baAmChart/index.ts
src/app/theme/components/baBackTop/index.ts
src/app/theme/components/baChartistChart/index.ts
src/app/theme/components/baContentTop/index.ts
src/app/theme/components/baFullCalendar/index.ts
src/app/theme/components/baMenu/index.ts
src/app/theme/components/baMsgCenter/index.ts
src/app/theme/components/baPageTop/index.ts
src/app/theme/components/baPictureUploader/index.ts
src/app/theme/components/baSidebar/index.ts
src/app/theme/directives/baScrollPosition/index.ts
src/app/theme/directives/baSlimScroll/index.ts
src/app/theme/directives/baThemeRun/index.ts
src/app/theme/pipes/baAppPicture/index.ts
src/app/theme/pipes/baKameleonPicture/index.ts
src/app/theme/pipes/baProfilePicture/index.ts
src/app/theme/services/baThemePreloader/index.ts

please show an option like you did in blur-admin to download html/js/css. thanks for share!
you're amazing!

what if I want to download just the html/js/css files?

---

.gitignore
config/electron/webpack.electron.common.js
config/electron/webpack.electron.dev.js
config/electron/webpack.electron.prod.js
config/electron/webpack.renderer.common.js
config/electron/webpack.renderer.dev.js
config/electron/webpack.renderer.prod.js
config/webpack.prod.js
package.json
src/app/environment.ts
src/desktop.ts
src/package.json

An updated feature 
Rudimentary integration
Complete integration with application and main being packed as Webpack.
New task to handle Electron builds. (ref: #96. #230)

Complete Electron integration (with Angular 2.0 stable)

---

src/app/theme/components/baSidebar/baSidebar.scss
src/app/theme/sass/_layout.scss
src/app/theme/sass/conf/_variables.scss

Sidebar is not quite configurable. It's needed to add ability to easily change its width

feat(sidebar): add ability to customize sidebar styles

---

config/electron/webpack.electron.common.js
config/electron/webpack.renderer.common.js

fix(electron): fix electron build

---

src/app/theme/components/baPageTop/baPageTop.scss

Bug
Logo text is difficult to see when logo is hovered
Logo color is changed

fix(logo): hover color of logo is changed

---

src/app/pages/ui/components/buttons/buttons.html
src/app/pages/ui/components/buttons/buttons.scss
src/app/pages/ui/components/buttons/components/dropdownButtons/dropdownButtons.html
src/app/theme/components/baPageTop/baPageTop.scss

Feature
Fixed ui.buttons page: maked widgets and buttoms more adaptive

Fix ui buttons page

---

package.json
src/app/pages/editors/components/ckeditor/ckeditor.loader.ts
src/app/theme/components/baPageTop/baPageTop.scss

Bug
Ckeditor doesnt show
Fixed ckeditor
Updated path to ckeditor cdn

#466 ckeditor not showing

---

CHANGELOG.md
_VERSION
package.json

chore(version): bump version to 0.8 (angular 2.2.3)

---

package.json
src/app/app.component.ts

Bug
Ng2-bootstrap modals doesnt work
Modals work
There is bug in ng2-bootstrap, which will be fixed in new release. I added temporary fix for it

fix(bug): temporary fix for ng2-bootstrap modals

---

config/head-config.common.js

Bug
Assets have an absolute path
Added relative path for assets

fix(bug): deleted absolute path for assets

---

src/app/pages/login/login.html

col-sm-offset to offset-sm-2

---

package.json
postcss.config.js

fix(PostCSS ) - added postcss config file

---

package.json
src/app/app.component.ts
src/app/pages/forms/forms.module.ts
src/app/pages/ui/ui.module.ts

Bug fix
Temporary fix https://github.com/akveo/ng2-admin/pull/493
Newer ng2-bootstrap version does not have this issue.
Newer ng2-bootstrap version also provides more components like popover etc.

fix modals issue by updating ng2-bootstrap to 1.3.0

---

docs/contents/articles/014-switch-to-blur-theme/index.md

This is a fix for documentation

fix for documentation

---

README.md

* **What kind of change does this PR introduce?**
Doc update (fix)
* **What is the current behavior?**
Readme license header invalid MarkDown format
* **What is the new behavior?**
Fix license header format by applying proper md formatting

docs(readme): fix licence header

---

package.json
src/app/theme/initial.scss
src/app/theme/sass/_fonts.scss
src/index.html
yarn.lock

- add (font) add Roboto font via npm

---

.bootstraprc
package.json
src/app/app.module.ts
src/app/pages/dashboard/pieChart/pieChart.scss
src/app/pages/dashboard/popularApp/popularApp.scss
src/app/pages/forms/components/inputs/components/checkboxInputs/checkboxInputs.component.ts
src/app/pages/forms/components/inputs/components/ratinginputs/ratinginputs.html
src/app/pages/ui/components/grid/grid.html
src/app/pages/ui/components/icons/icons.html
src/app/pages/ui/components/modals/default-modal/default-modal.component.html
src/app/pages/ui/components/modals/default-modal/default-modal.component.scss
src/app/pages/ui/components/modals/default-modal/default-modal.component.ts
src/app/pages/ui/components/modals/modals.component.ts
src/app/pages/ui/components/modals/modals.html
src/app/pages/ui/ui.module.ts
src/app/theme/components/baCheckbox/baCheckbox.component.ts
src/app/theme/components/baMultiCheckbox/baMultiCheckbox.component.ts
src/app/theme/components/baMultiCheckbox/baMultiCheckbox.html
src/app/theme/components/baMultiCheckbox/baMultiCheckbox.scss
src/app/theme/sass/_buttons.scss
src/app/theme/sass/_form.scss
src/app/theme/sass/_modal.scss
src/app/theme/sass/_table.scss
src/app/theme/sass/_typography.scss
src/app/theme/theme.scss
yarn.lock

Bootstrap upgrade

---

src/app/pages/ui/ui.module.ts

fix(ui): fix NgbModal declaration

---

src/app/environment.ts

fix(build): fix #955

---

src/app/pages/dashboard/dashboard.html
src/app/pages/dashboard/pieChart/pieChart.html
src/app/pages/dashboard/popularApp/popularApp.html
src/app/pages/ui/components/buttons/components/dropdownButtons/dropdownButtons.html
src/app/pages/ui/components/buttons/components/largeButtons/largeButtons.html
src/app/pages/ui/components/typography/typography.html

fix(style): fix #958 component size for small screen

---

src/app/pages/tables/components/basicTables/components/responsiveTable/responsiveTable.html
src/app/theme/sass/bootstrap-overrides/_card.scss

fix(style): fix #962 height card bug in Safari

---

src/app/theme/components/baMenu/baMenu.html

refactor(menu): refactor #965 excess aside tag

---

src/app/theme/components/baMsgCenter/baMsgCenter.html

Removed hard-coded message and notification count and used array length instead.

notification and message count from array length

---

src/app/theme/components/baPageTop/baPageTop.html
src/app/theme/components/baPageTop/baPageTop.scss

This changes the HTML/CSS that shows the profile dropdown arrow pointing at the picture.
The current arrow in the dropdown menu is a list item. That's visible on hover in the dropdown though. 
The new behavior shows the arrow on the top of the dropdown but doesn't have the extra space and empty list item that is visible on hover.
YAY!

Dropdown arrow 

---

src/app/pages/forms/components/layouts/layouts.component.ts
src/app/pages/forms/components/layouts/layouts.html
src/app/theme/components/baFileUploader/baFileUploader.component.ts
src/app/theme/components/baFileUploader/baFileUploader.html
src/app/theme/components/baFileUploader/index.ts
src/app/theme/components/index.ts
src/app/theme/nga.module.ts

feature :yum:
FileUploader ui to use comfortably in form layouts
Add FileUploader component in form layouts

Add FileUploader

---

docs/contents/articles/011-changing-color-scheme/index.md

fix typo of theme file to copy

---

src/app/pages/login/login.html
src/app/pages/login/login.module.ts
src/assets/i18n/US/en.json

Translation and Locale Updates
Login Pages Labels are hard coded in Template.
Dashboard, Pages Labels is localized and it served from src/assets/i18n/US/en.json

Added the Locale Changes for Login Page

---

CHANGELOG.md
README.md
_VERSION
package.json
yarn.lock

docs: update changelog for 1.0.0

---

CHANGELOG.md
docs/contents/articles/001-getting-started/index.md
docs/contents/articles/002-installation-guidelines/index.md
docs/contents/articles/011-changing-color-scheme/index.md
docs/contents/articles/012-project-structure/index.md
docs/contents/articles/013-create-new-page/index.md
docs/contents/articles/014-switch-to-blur-theme/index.md
docs/contents/articles/015-sidebar/index.md
docs/contents/articles/016-spinner/index.md
docs/templates/index.jade
docs/templates/layout.jade
package.json
yarn.lock

docs: update docs for 1.0.0

---

.angular-cli.json
package.json
src/app/pages/pages.menu.ts
src/app/pages/tables/components/hotTables/handsontable-section.ts
src/app/pages/tables/components/hotTables/handsontable/advanced-demo.ts
src/app/pages/tables/components/hotTables/handsontable/science-demo.service.ts
src/app/pages/tables/components/hotTables/handsontable/science-demo.ts
src/app/pages/tables/components/hotTables/hotTables.scss
src/app/pages/ui/components/slim/index.ts
src/app/pages/ui/components/slim/slim.component.ts
src/app/pages/ui/components/slim/slim.html
src/app/pages/ui/components/slim/slim.scss
src/app/pages/ui/ui.module.ts
src/app/pages/ui/ui.routing.ts
yarn.lock

add slimLoadingBar in ng2-admin

add slimLoadingBar Library to ui

---

src/framework/theme/components/search/search.component.ts

fix(search): unsubscribe observables

---

src/app/pages/charts/components/chartistJs/chartistJs.html
src/app/pages/components/components/treeView/treeView.html
src/app/pages/dashboard/dashboard.html
src/app/pages/editors/components/ckeditor/ckeditor.html
src/app/pages/forms/components/inputs/inputs.html
src/app/pages/forms/components/layouts/layouts.html
src/app/pages/maps/components/bubbleMaps/bubbleMaps.html
src/app/pages/maps/components/googleMaps/googleMaps.html
src/app/pages/maps/components/leafletMaps/leafletMaps.html
src/app/pages/maps/components/lineMaps/lineMaps.html
src/app/pages/tables/components/basicTables/basicTables.html
src/app/pages/tables/components/hotTables/handsontable-section.ts
src/app/pages/tables/components/smartTables/smartTables.html
src/app/pages/ui/components/buttons/buttons.html
src/app/pages/ui/components/grid/grid.html
src/app/pages/ui/components/icons/icons.html
src/app/pages/ui/components/modals/modals.html
src/app/pages/ui/components/slim/slim.html
src/app/pages/ui/components/typography/typography.html
src/app/theme/components/baCard/baCard.component.ts
src/app/theme/components/baCard/baCard.html

Bug Fix: Issue using title attribute in Custom Component.
Bcard Component used `title` which is showing as title. In localization use cases. its showing the locale variable.
Updated the new Input for Component named `cardTitle` which resolved this issue.
Screenshot is below.

Updated the B Card Component Input from title to cardTitle

---

DEV_DOCS.md

I really think some contributors have difficulties with starting development. So maybe it's a good idea to provide them the small guide.

docs(dev-docs): add dev docs

---

src/app/pages/dashboard/contacts/contacts.component.scss

Fixed typo in css attribute for https://github.com/akveo/ngx-admin/issues/1424

Fixed typo in styles

---

src/app/@theme/layouts/sample/sample.layout.ts

fix(demo): add support us link

---

src/app/@theme/components/header/header.component.html
src/app/@theme/components/header/header.component.scss

feat(demo): add github star button

---

.angular-cli.json
package-lock.json
package.json
src/app/@core/core.module.ts

Closes #1515
- [x ] I read and followed the [CONTRIBUTING.md](https://github.com/akveo/ngx-admin/blob/master/CONTRIBUTING.md) guide.
- [x ] I read and followed the [New Feature Checklist](https://github.com/akveo/ngx-admin/blob/master/DEV_DOCS.md#new-feature-checklist) guide.

feat(auth): configurable auth social icons

---

src/app/pages/dashboard/temperature/temperature.component.html

fix(dashboard): update btn group toggle html

---

src/app/app.module.ts

refactor(http): replace old http with a new one

---

src/app/pages/maps/search-map/entity/Location.ts

- [ x] I read and followed the [CONTRIBUTING.md](https://github.com/akveo/ngx-admin/blob/master/CONTRIBUTING.md) guide.
- [ x] I read and followed the [New Feature Checklist](https://github.com/akveo/ngx-admin/blob/master/DEV_DOCS.md#new-feature-checklist) guide.

Set default location Minsk

---

README.md

docs(readme): readme images update

---

.travis.yml

chore: node version update

---

CHANGELOG.md
package-lock.json
package.json

release: v2.2.0 RTL & Angular 6 release

---

README.md

update README for ng 6.x

---

src/app/pages/ui-features/buttons/button-groups/button-groups.component.html

Fix checkbox for https://github.com/akveo/ngx-admin/issues/1697

fix(buttons): Uncheck checkbox after click

---

package-lock.json
package.json
src/app/pages/components/components.module.ts

Update toaster version for https://github.com/akveo/ngx-admin/issues/1656

feat(toaster): update toaster to latest version (6.0.0)

---

CONTRIBUTING.md

Update contributing docs, fix for https://github.com/akveo/ngx-admin/issues/1673

docs: update contributing docs

---

src/app/@theme/styles/font-size.scss
src/app/@theme/styles/styles.scss

feat(app): set default font-size to 14px

---

README.md

fix(readme): update docs link

---

src/app/@theme/components/theme-switcher/theme-switcher.component.scss
src/app/@theme/styles/themes.scss
src/app/pages/dashboard/dashboard.component.ts
src/app/pages/dashboard/temperature/temperature-dragger/temperature-dragger.component.ts

fix(temperature): fix temperature dragger gradient

---

README.md

feat(readme): add new theme

---

CHANGELOG.md
package-lock.json
package.json

release: v2.3.0

---

README.md

Wrong URL Starter Kit documentation

fix(readme): update doc (starter kit) link

---

CONTRIBUTING.md

Fixed a typo in Type section in CONTRIBUTING.md

Fixed a typo in Type in CONTRIBUTING.md

---

angular.json

This PR automatically adds a `prefix` in `angular.json`, let ng-cli can automatically build a correct selector in a Component.

add prefix: ngx-

---

README.md

docs(readme): add ecommerce template

---

src/app/pages/ui-features/buttons/size-buttons/size-buttons.component.html

Fixes button styling of tiny button on page
http://akveo.com/ngx-admin/#/pages/ui-features/buttons

docs(nx-admin buttons example): change tiny button class to xsmall

---

CHANGELOG.md
package-lock.json
package.json

update package versions, update changelog

---

src/app/@theme/layouts/sample/sample.layout.scss

remove label 'new' from sidebar

---

src/app/pages/pages.component.scss

fix datepicker arrow style

---

src/app/@core/utils/analytics.service.ts
src/app/@theme/components/header/header.component.ts
src/app/@theme/components/theme-switcher/themes-switcher-list/themes-switcher-list.component.ts
src/app/app.component.ts

feat(analytics): update analytics service, use google tag manager

---

src/app/@theme/components/banner/banner.component.ts

feat(banner): update banner link

---

docs/app/pages/home/landing-home.component.html
docs/app/pages/home/landing-home.component.scss

don't hunt me ribbon added for landing

feat(ribbon): don't hunt me ribbon added

---

docs/app/pages/home/landing-home.component.html
docs/app/pages/home/landing-home.component.scss
docs/app/pages/home/landing-home.module.ts
docs/app/pages/home/ribbon/ribbon.component.html
docs/app/pages/home/ribbon/ribbon.component.scss
docs/app/pages/home/ribbon/ribbon.component.ts

"Don't hunt me" ribbon moved to separate component

fix(ribbon): ribbon moved to separate component

---

README.md

docs(readme): update images

---

src/app/pages/pages.component.scss

add fade in animation by route change

---

src/app/@theme/components/header/header.component.ts

style(header): remove unused method

---

src/app/@core/utils/ab.service.ts
src/app/pages/dashboard/dashboard.component.html
src/app/pages/dashboard/dashboard.component.ts
src/app/pages/e-commerce/e-commerce.component.html
src/app/pages/e-commerce/e-commerce.component.ts

ab-service added to show or hide call to action cards

feat: call to action cards ab test

---

README.md

docs: update readme with PH link

---

README.md

docs(readme): remove PH note

---

docs/app/pages/home/banner/banner.component.ts
src/app/@theme/components/banner/banner.component.ts

Use relative URL to load respecting to base href

fix(banner): use relative img url

---

README.md

fix(readme): fix demo links

---

src/app/@theme/components/header/header.component.scss

fix(demo): button vertical alignment

---

src/app/@theme/layouts/sample/sample.layout.scss
src/app/pages/extra-components/progress-bar/interactive-progress-bar/interactive-progress-bar.component.ts

Settings sidebar Ie and firefox position bugs, fix linted file

fix(setting-sidebar): Ie and firefox position bugs, linter

---

src/app/pages/pages.component.scss

This change removes the hotfix introduced to fix the issue [#1006](https://github.com/akveo/nebular/issues/1006), which is resolved by now.

Removed hotfix for issue 1006

---

README.md

docs: add link to store in readme

---

docs/app/pages/home/theme-section/theme-section.component.html
docs/app/pages/home/theme-section/theme-section.component.scss

Feat(landing): add links to slides in theme slider

---

src/app/pages/pages-menu.ts

fix(sidebar): Add Form Inputs extra component menu item

---

docs/app/@core/data/service/bundles.service.ts

correct prices to make it consistent with store

fix(bundles): fix prices to make consistent with store

---

docs/app/@core/data/service/bundles.service.ts
docs/app/pages/home/backend-bundles-section/backend-bundles-section.component.html
docs/app/pages/home/backend-bundles-section/backend-bundles-section.component.scss
docs/app/pages/home/backend-bundles-section/backend-bundles-section.component.ts
docs/app/pages/home/backend-bundles-section/background-image.pipe.ts
docs/app/pages/home/landing-home.module.ts

Fix styles, improve code of service and component

feat(store): styling fix, code improvement

---

README.md

chore: update readme images

---

CHANGELOG.md
package-lock.json
package.json

release: 4.0.0

---

src/app/pages/e-commerce/traffic-reveal-card/front-side/traffic-front-card.component.html
src/app/pages/e-commerce/traffic-reveal-card/front-side/traffic-front-card.component.scss

refactor(traffic card): remove unused styling

---

README.md

chore: change dark theme readme image

---

README.md

chore(readme): update Angular version to 8

---

CHANGELOG.md
package-lock.json
package.json

release: 4.0.1

---

README.md

Typo in README. Should be 4 themes.

Update README for extra theme

---

docs/app/pages/home/main-info-section/main-info-section.component.html

feat: add store link

---

src/app/@theme/components/tiny-mce/tiny-mce.component.ts

Otherwise TinyMCE generates url relative to current page

fix(tinymce): set absolute path for skin url

---

angular.json
docs/google46533d2e7a851062.html
docs/google85b6c09017edfbcb.html

chore: update google verification

---

src/app/pages/forms/forms.module.ts

Resolve forms layout resfresh
#2156
The forms layout page no longer refreshes when pressing the form submit buttons

fix(forms): add missing forms module import

---

README.md

chore(readme): update bundles image

---

README.md

chore: add bundles black friday deal

---

README.md

chore(readme): update black friday 2019 image

---

README.md

chore(readme): remove bundles discounts image

---

src/app/@core/core.module.ts
src/app/@core/utils/index.ts
src/app/@core/utils/seo.service.ts
src/app/app.component.ts

feat(seo): add canonical tag

---

docs/app/@theme/components/header/header.component.html
docs/app/pages/docs/landing-docs.component.html
docs/articles/index.md

chore(docs): replace email with SO and GitHub links

---

docs/app/pages/home/main-info-section/main-info-section.component.html
docs/app/pages/home/main-info-section/main-info-section.component.scss

feat: update bundles text

---

README.md
docs/app/@theme/components/docs-footer/footer.component.html
docs/app/@theme/components/footer/footer.component.html
docs/app/pages/home/backend-bundles-section/backend-bundles-section.component.html
docs/app/pages/home/contact-section/contact-section.component.html
docs/app/pages/home/main-info-section/main-info-section.component.html
docs/app/pages/home/our-projects-section/our-projects-section.component.html
docs/app/pages/home/reason-section/reason-section.component.html
docs/app/pages/home/theme-section/theme-section.component.html
docs/articles/concept-theme-system.md
docs/articles/index.md
src/app/@theme/components/footer/footer.component.ts
src/app/pages/dashboard/dashboard.component.html
src/app/pages/dashboard/kitten/kitten.component.html
src/app/pages/e-commerce/e-commerce.component.html
src/app/pages/ui-features/icons/icons.component.html

chore(analytics): add proper analytics tracking URLs

---

README.md

chore: update readme bundles section

---

CHANGELOG.md
package-lock.json
package.json

release: 5.0.0

---

README.md

chore(readme): Angular 9 and Material theme info

---

src/app/pages/dashboard/electricity/electricity-chart/electricity-chart.component.ts
src/app/pages/e-commerce/charts-panel/charts/orders-chart.component.ts
src/app/pages/e-commerce/visitors-analytics/visitors-analytics-chart/visitors-analytics-chart.component.ts

fix(echarts): set merge input

---

README.md

chore(readme): reduce image size

---

docs/app/@theme/styles/_swiper_ngx-admin.scss
docs/app/pages/home/reviews-section/reviews-section.component.scss
docs/app/pages/home/theme-section/theme-section.component.scss

Add mixin for styling swiper arrows and fix styles for arrows

Swiper arrows fix on demo

---

docs/app/@core/data/service/bundles.service.ts

fix(demo): update bundle uri

---

src/app/@core/utils/layout.service.ts
src/app/pages/dashboard/electricity/electricity-chart/electricity-chart.component.ts
src/app/pages/dashboard/traffic/traffic-chart.component.ts
src/app/pages/e-commerce/charts-panel/charts/orders-chart.component.ts
src/app/pages/e-commerce/charts-panel/charts/profit-chart.component.ts
src/app/pages/e-commerce/country-orders/chart/country-orders-chart.component.ts
src/app/pages/e-commerce/earning-card/front-side/earning-live-update-chart.component.ts
src/app/pages/e-commerce/profit-card/back-side/stats-area-chart.component.ts
src/app/pages/e-commerce/profit-card/front-side/stats-bar-animation-chart.component.ts
src/app/pages/e-commerce/profit-card/profit-card.component.scss
src/app/pages/e-commerce/traffic-reveal-card/back-side/traffic-bar-chart.component.ts
src/app/pages/e-commerce/visitors-analytics/visitors-analytics-chart/visitors-analytics-chart.component.ts
src/app/pages/e-commerce/visitors-analytics/visitors-statistics/visitors-statistics.component.ts

Improve performance after menu toggle

Master sidebar performance improve

---

src/app/pages/pages-menu.ts

Add backend integration menu items

feat: add backend integration menu pages

---

docs/app/pages/docs/page/ngx-admin-landing-page.component.ts

fix: title in docs

---

.github/workflows/ACTION_TRIGGER_GUIDE.md
.github/workflows/demoDeploy.yml

Feat: create deploy demo script

---

.github/workflows/demoDeploy.yml

fix deploy demo script

---

.github/workflows/ACTION_TRIGGER_GUIDE.md
.github/workflows/demoDeploy.yml
.github/workflows/docsDeploy.yml

Feat:  create docs deploy script

---

.github/workflows/docsDeploy.yml

fix deploy docs script

---

.github/workflows/docsDeploy.yml

fix deploy script

---

.github/workflows/docsDeploy.yml

fix: update docs yaml

---

.github/workflows/docsDeploy.yml

fix: fix deploy script

---

.github/workflows/ACTION_TRIGGER_GUIDE.md
.github/workflows/demoDeploy.yml
.github/workflows/docsDeploy.yml

feat: add guthub actions

---

README.md

feat: update banner links

---

README.md

feat: update starter kit banner links

---

src/app/pages/pages-menu.ts

feat: update navigation links

---

README.md

docs(readme): add banner to readme with free bundle

---

README.md

docs(readme): add free banner to read me

---

docs/app/@core/data/service/bundles.service.ts
docs/app/pages/home/backend-bundles-section/backend-bundles-section.component.html

docs(bundle): update bundle section, show collection list

---

docs/app/pages/home/material-landing/material-landing.component.html
docs/app/pages/home/sections-container/ngx-landing-sections-container.component.html

chore: update dot net bundle link

---

CHANGELOG.md
package-lock.json
package.json

release: 6.0.0

---

README.md

chore(readme): update Angular version

---

README.md
docs/app/@theme/components/docs-footer/footer.component.html
docs/app/@theme/components/footer/footer.component.html
docs/app/pages/home/backend-bundles-section/backend-bundles-section.component.html
docs/app/pages/home/contact-form/contact.component.html
docs/app/pages/home/contact-section/contact-section.component.html
docs/app/pages/home/main-info-section/default-admin-main-info/default-info.component.html
docs/app/pages/home/main-info-section/main-info-section.component.html
docs/app/pages/home/main-info-section/material-admin-main-info/material-info.component.html
docs/app/pages/home/our-projects-section/our-projects-section.component.html
docs/app/pages/home/reason-section/reason-section.component.html
docs/app/pages/home/theme-section/theme-section.component.html
docs/articles/concept-theme-system.md
docs/articles/index.md
src/app/@theme/components/footer/footer.component.ts
src/app/pages/dashboard/dashboard.component.html
src/app/pages/dashboard/kitten/kitten.component.html
src/app/pages/e-commerce/e-commerce.component.html
src/app/pages/pages-menu.ts
src/app/pages/ui-features/icons/icons.component.html

Revert short links back to long variants

chore(demo): revert short links back to full ones

---

README.md
src/app/pages/dashboard/kitten/kitten.component.html
src/app/pages/ui-features/icons/icons.component.html

Change short links back to full ones

chore(docs): revert docs external links back to long variants

---

docs/index.html

feat(demo): integrated hotjar to ngx-admin docs

---

docs/app/@core/data/data.module.ts

fix(docs): use generic module with providers

---

docs/tsconfig.app.json

fix(docs): use correct tsconfig file

---

docs/app/pages/home/sections-container/ngx-landing-sections-container.component.html

feat(demo): moved backend block up in landing

---

docs/app/pages/home/main-info-section/default-admin-main-info/default-info.component.html
docs/app/pages/home/main-info-section/main-info-section.component.html
docs/app/pages/home/our-projects-section/our-projects-section.component.html
docs/app/pages/home/social-section/social-section.component.html
docs/app/pages/home/theme-section/theme-section.component.html

feat(demo): changed links in landing

---

README.md

chore(readme): add templates link

---

docs/app/shared/components/premium-form/premium-form.component.ts

fix(admin premium form): don't redirect to GitHub

---

docs/app/pages/home/main-info-section/main-info-section.component.html
docs/app/pages/home/main-info-section/main-info-section.component.scss

feat: added update subscription button

---

CHANGELOG.md
package-lock.json
package.json

release: 7.0.0

---

docs/app/pages/home/backend-bundles-section/backend-bundles-section.component.html

fix: correct fleet management banner path

---

README.md

chore(readme): add bakery banner

---

.github/workflows/docsDeploy.yml

chore(docs deploy): lock node version

---

.github/workflows/azureCliDeploy.yml

feat(deploy): enable manual triggering

---

.github/workflows/ACTION_TRIGGER_GUIDE.md
.github/workflows/azureCliDeploy.yml
.github/workflows/docsDeploy.yml

Demo enable gh actions manual trigger

---

src/app/pages/pages-menu.ts
src/app/pages/pages-routing.module.ts

chore: remove bundles pages

---

CHANGELOG.md
README.md
package.json

release: 9.0.0

---

package-lock.json
src/app/pages/dashboard/rooms/rooms.component.ts
src/app/pages/e-commerce/country-orders/chart/country-orders-chart.component.ts
src/app/pages/e-commerce/country-orders/country-orders.component.ts

fix: fix issues after updates to Angular 13 in rooms component and country orders component

---

CHANGELOG.md
package.json

release: 10.0.0

---

README.md
package-lock.json

* fix(package-lock): update version in package-lock

fix(package-lock): update version in package-lock

---

src/app/@theme/styles/material/_material-overrides.scss
src/app/@theme/styles/themes.scss

fix(material-theme): fix style for material theme, disable custom css custom properties for material theme

---

CHANGELOG.md
package-lock.json
package.json

release: 11.0.0

---

scripts/docs/build-docs.ts

fix(demo-build): fix demo build

---

.github/workflows/docsDeploy.yml

fix(demo-build): fix demo build deployment

---

docs/main.ts

fix(demo-build): run demo build

---

.github/workflows/docsDeploy.yml
docs/main.ts
scripts/docs/build-docs.ts

fix(demo-build): fix demo dosc deployments
