src/app/theme/sass/_preloader.scss
Performance fix
Preloader spinner janks on Firefox on Linux on Intel Broadwell 
Preloader spinner spins smoothly
Using the backface-visibility property causes 2D elements and transforms
to be elevated to a 3D context. Since the only transform being used is
rotate(Xdeg), which is a 2D transform, there is no need to incur the
extra performance penalty.
=> Improve preloader performance on non-accelerated platforms

typings.json
Bug Fix
Typings install has no affect!
Typings install will do its job! :)
Using "typings install" has no function because ambientDependencies is deprecated.
With globalDependencies, typings install does its job again! :-)
=> Changing deprecated ambientDependencies to globalDependencies

src/app/theme/components/baSidebar/baSidebar.html
**bug** - sidebar angle icon not pointing up when menu with subitems expanded
**current behavior** - sidebar angle icon not pointing up when menu with subitems expanded
- sidebar angle icon DO pointing up when expanded
Thanks
=> trying to fix issue sidebar angle icon no pointing up when expanded

config/webpack.dev.js, config/webpack.prod.js
- **What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Bug Fix
- **What is the current behavior? (You can also link to an open issue here)**
The generated source map file for main.bundle.js only contains the following incorrect content.
> {"version":3,"sources":[],"names":[],"mappings":"","file":"initial.css","sourceRoot":""}
- **What is the new behavior (if this is a feature change)?**
The whole source mappings will be produced properly.
- **Other information:**
https://github.com/webpack/extract-text-webpack-plugin/issues/119
=> Make source map files generated correctly.

src/app/theme/components/baSidebar/baSidebar.component.ts
Fixing navigation issue
When creating the menu form the routes objects, the routes object shouldn't be changed since the next time it will be used by the menu, it will be corrupted.  
Creating a clone of the routes object before changing it.
issue 93 describes the problem.
=> fixing navigation issue - creating deep copy of routes before working on

package.json
Hi,
With the last current version, I get this error:
```
ERROR in ./~/font-awesome-sass-loader/index.js
Module not found: Error: Can't resolve './font-awesome-sass-styles' in 'node_modules/font-awesome-sass-loader'
@ ./~/font-awesome-sass-loader/index.js 1:0-82
@ ./src/vendor.browser.ts
@ multi vendor
```
After research, it's a bug of the package `font-awesome-sass-loader` fixed in the [version 1.0.2](https://github.com/francisbesset/font-awesome-sass-loader/compare/v1.0.1...v1.0.2).
To avoid this kind of problem, I changed the minimal version of the package.
I couldn't build the production project, I get this error which seems unrelated to `font-awesome-sass-loader` package:
```
Error in bail mode: [default] src/app/pages/editors/components/ckeditor/ckeditor.component.ts:2:8
Module …
```
=> Fix an issue about the font-awesome-sass-loader.

src/app/theme/components/baAmChart/index.ts, src/app/theme/components/baBackTop/index.ts, src/app/theme/components/baChartistChart/index.ts, src/app/theme/components/baContentTop/index.ts, src/app/theme/components/baFullCalendar/index.ts, src/app/theme/components/baMenu/index.ts, src/app/theme/components/baMsgCenter/index.ts, src/app/theme/components/baPageTop/index.ts, src/app/theme/components/baPictureUploader/index.ts, src/app/theme/components/baSidebar/index.ts, src/app/theme/directives/baScrollPosition/index.ts, src/app/theme/directives/baSlimScroll/index.ts, src/app/theme/directives/baThemeRun/index.ts, src/app/theme/pipes/baAppPicture/index.ts, src/app/theme/pipes/baKameleonPicture/index.ts, src/app/theme/pipes/baProfilePicture/index.ts, src/app/theme/services/baThemePreloader/index.ts
I'm using Visual Studio & Resharper, and some imports/exports weren't recognized. 
Changing them to not include .ts extension fixes this.
=> Remove extensions from imports/exports

config/webpack.common.js, package.json, src/electron/main.js
Based on #96, and because I want to use this wonderful project as the basis for a new electron app, I implemented a rudimentary wrapper for electron as a POC. I will extend this functionality on the electron part to include packaging, optimizations (removing polyfills etc.) later on.
I would suggest creating a feature branch for this, so it can mature further before becoming an integral part of ng2-admin.
ng2-admin runs as a web application.
ng2-admin can now also be run as an electron app.
The only change to ng2-admin itself is changing the …
=> Rudimentary support for electron

src/app/pages/forms/components/inputs/components/selectInputs/index.ts, src/app/pages/forms/components/inputs/components/selectInputs/selectInputs.component.ts, src/app/pages/forms/components/inputs/components/selectInputs/selectInputs.html, src/app/pages/forms/components/inputs/inputs.html, src/app/pages/forms/forms.module.ts, src/app/theme/sass/_form.scss
Feature
There are no select dropdowns on the _form inputs_ page. The select dropdown options have invalid colors, which makes them unusable without additional styling.
Add a new card to the _form inputs_ page presenting two types of select dropdowns, allowing for single and multiple options selection. Options are now correctly styled.
I tried to mimic how other components are added to the panel. Let me know if there's anything wrong.
Related to issue #282
=> feat(forms): add example selects with valid styling

src/app/theme/components/baMenu/baMenu.service.ts
Bug fix
Menu item link contains extra '/' for empty string path component. Please see https://github.com/akveo/ng2-admin/issues/364.
Prevent extra '/'.
n/a
=> fix(menu): prevent extra '/' in menu link for empty path string

package.json, src/app/pages/forms/components/inputs/components/ratinginputs/ratinginputs.html, src/app/pages/forms/forms.module.ts, src/app/pages/ui/components/buttons/components/dropdownButtons/dropdownButtons.html, src/app/pages/ui/ui.module.ts
Bug fix
Dropdown and Modal don't work.
Remove ng2-bootstrap components. Use ng-bootstrap components instead. All bootstrap components should work properly.
ng2-bootstrap and ng-bootstrap provide much similar functionalities. We should use only one of them in order to avoid conflicts.
=> fix(dependencies): replace ng2-bootstrap with ng-bootstrap

package.json, src/app/app.module.ts, src/app/app.translation.module.ts, src/app/pages/dashboard/dashboard.html, src/app/pages/dashboard/dashboard.module.ts, src/app/pages/dashboard/pieChart/pieChart.html, src/app/pages/dashboard/pieChart/pieChart.service.ts, src/app/pages/forms/components/inputs/components/checkboxInputs/checkboxInputs.html, src/app/pages/forms/forms.module.ts, src/app/pages/pages.menu.ts, src/app/theme/components/baCard/baCard.html, src/app/theme/components/baContentTop/baContentTop.html, src/app/theme/components/baMenu/components/baMenuItem/baMenuItem.html, src/app/theme/nga.module.ts, src/assets/i18n/US/en.json
- Localization Module base Setup.
- Implemented in the Page Heading, Breadcrumb and Menu Link Title, Dashboard and one Form Element.
Localization Feature to Keep text in one file and that can be changed according to the country and language.
All Text Labels are hard coded in the Code.
Few Page's Text Labels are moved to one file and its dynamic according to the country and language.
Currently implemented with `ngx-translate` for basic blocks. if this implementation is fine, please goahead and merge so that i can complete this for the entire …
=> Implemented the Localization using ngx-translate Module

src/app/pages/forms/components/layouts/components/blockForm/blockForm.html
Bug fix, now if you click on the label email it will select the right input.
If you click on email label the name input will be selected.
=> Bad linking correction between label and input

config/webpack.dev.js
Bug fix.
when PORT env variable exist, npm start failed with an error
```
Invalid configuration object. webpack-dev-server has been initialised using a configuration object that does not match the API schema.
- configuration.port should be a number.
```
this PR fix the issue.
=> fix a bug when PORT env exist.

src/app/pages/charts/charts.module.ts, src/app/pages/charts/components/chartistJs/chartistJs.html, src/app/pages/components/components/treeView/treeView.html, src/app/pages/dashboard/dashboard.html, src/app/pages/dashboard/pieChart/pieChart.service.ts, src/app/pages/dashboard/popularApp/popularApp.html, src/app/pages/dashboard/todo/todo.html, src/app/pages/dashboard/trafficChart/trafficChart.html, src/app/pages/pages.component.ts, src/app/pages/pages.module.ts, src/assets/i18n/US/en.json
Translation and Locale Updates
Dashboard, Pages, Traffic chart, Popular App, Tree View and Chart JS Labels are hard coded in Template.
Dashboard, Pages, Traffic chart, Popular App, Tree View and Chart JS Labels is localized and it served from `src/assets/i18n/US/en.json`
=> Updated the Translation Support

src/app/pages/tables/components/smartTables/smartTables.scss
=> fix(smart-table): fix #1000 smart table style bug

src/app/app.component.ts
Absolute image path causing problems when app is not run in a root directory.
=> Bug fix: Absolute image path

src/app/theme/sass/bootstrap-overrides/_card.scss
Fix Bug #1171 (baCard with scrollbar not displaying in IE11)
Bug fix
baCards with scrolling are not displayed correctly in IE11.  See bug #1171 
baCards with scrolling are displayed correctly in IE11
=> Fix Bug #1171 (baCard with scrollbar not displaying in IE11)

src/main.ts
Support for Angular Prod Mode when in production==true in environment.
Otherwise, you have warning that Angular is in development mode in console.log when run in production.
=> Update main.ts for enableProdMode();

Dockerfile, package.json
**What kind of change does this PR introduce?**
Bug fix.
**What is the current behavior?**
Running the following command:
`docker build -t <your username>/node-web-app .`
Produces the following error:
`npm ERR! missing script: clean`
`npm ERR! missing script: prebuild:prod`
**Other information**:
Added `clean` command to **package.json**.
Replaced `prebuild:prod` `build:prod` commands with `build:prod:aot` in **Dockerfile**.
Changed entry point from `server:prod`to `start:prod`
=> Fixed error occurring with 'docker build'

.gitignore, package-lock.json, package.json
**What kind of change does this PR introduce?** 
Feature
**What is the new behavior (if this is a feature change)?**
this PR adds support for [compodoc](https://compodoc.github.io/website/) angular documentation generator (as discussed in #1326)
**Other information:**
`npm run docs` builds the documentations in `docs` folder.
`npm run docs:serve` builds the documentations and serves it on http://localhost:8080/
**More information:**
https://compodoc.github.io/website/guides/getting-started.html
https://github.com/compodoc/compodoc
=> add compodoc documentation generator

src/app/pages/components/notifications/notifications.component.html, src/app/pages/dashboard/traffic/traffic.component.ts
Some dropdown menu did not show up, because `ngbDropdown ` directive was used in the ul element instead of `ngbDropdownMenu`.
This issue appeared in the **notification** component page, and in the **traffic** section in the dashboard.
It works in the _live_ demo page, but did not work in my localhost before this correction.
=> Fix mistyped ngbDropdownMenu in some ngbDropdown ul elements

src/app/app.component.ts, src/app/pages/pages.component.ts
About this issue : https://github.com/akveo/ngx-admin/issues/1521
In the header, the change detection was not working automatically because change detection value was "ChangeDetectionStrategy.OnPush" in app and pages.
So I removed ChangeDetectionStrategy.OnPush in app.component and pages.component.
Now, the change detection values are "ChangeDetectionStrategy.Default".
=> fix(starter-kit): Change detection issue within AJAX call #1521

src/app/@theme/theme.module.ts, src/app/pages/pages-menu.ts, src/app/pages/ui-features/popovers/popover-examples.component.ts, src/app/pages/ui-features/popovers/popovers.component.html, src/app/pages/ui-features/popovers/popovers.component.scss, src/app/pages/ui-features/popovers/popovers.component.ts, src/app/pages/ui-features/ui-features-routing.module.ts, src/app/pages/ui-features/ui-features.module.ts
=> feat(popover): add popover showcase

src/app/@theme/components/index.ts, src/app/pages/dashboard/temperature/temperature-dragger/temperature-dragger.component.ts, tslint.json
The first parameter in the semicolon option in tslint.json should be a boolean.
Fixes the typescript linter
=> fix(tslint): add correct semicolon option

src/app/@theme/layouts/sample/sample.layout.ts
Fix ngx-toggle-settings-button position while search open
=> fix(toggle-settings-button): position while search open

package-lock.json, src/app/@theme/components/toggle-settings-button/toggle-settings-button.component.scss, src/app/@theme/components/toggle-settings-button/toggle-settings-button.component.ts
=> feat(layout config): reduce gear button size

src/app/pages/ui-features/typography/typography.component.html, src/app/pages/ui-features/typography/typography.component.scss
Use different class for basic text showcase. Bootstrap has !important
declaration in `text-body` class
=> fix(typography): prevent bootstrap color override

docs/404.html
Fixes accessing docs pages by direct link. Nebular uses special ghspa
script so we can't use it for ngx-admin.
=> fix(404 page): set correct base href

docs/app/@core/data/service/bundles.service.ts, docs/app/pages/home/backend-bundles-section/backend-bundles-section.component.html, docs/app/pages/home/backend-bundles-section/backend-bundles-section.component.ts, docs/app/pages/home/landing-home.module.ts
Hides crossed old price if it's 0 or something else converting to false.
Also changes item description paragraph tag reg epx to any tag reg exp as there was other tags used in description.
=> fix(bundles): hide old price if no discount

src/app/@core/core.module.ts, src/app/@core/utils/index.ts, src/app/@core/utils/seo.service.ts, src/app/app.component.ts
Adds a dynamic canonical tag that improves SEO
=> feat(seo): add canonical tag

docs/app/@core/data/service/bundles.service.ts, docs/app/pages/home/backend-bundles-section/backend-bundles-section.component.html, docs/app/pages/home/backend-bundles-section/backend-bundles-section.component.ts, docs/app/pages/home/backend-bundles-section/license.pipe.ts
=> fix(demo-docs): fix banners in backend bundles section

package-lock.json, package.json
Angular CDK introduced breaking change in the patch update (10.1.2).
https://github.com/akveo/nebular/issues/2487#issuecomment-682661879
Lock cdk version to 10.1.1.
CC #5753.
=> fix: downgrade Angular CDK
